# Generated by Django 4.2.4 on 2023-08-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="image1",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
