# Generated by Django 4.2.4 on 2023-08-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_newsletter_image1"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="topic1",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
